[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.24"
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
anvil = "http://127.0.0.1:8545"
ethereum = "${ETH_RPC_URL}"
polygon = "${POLYGON_RPC_URL}"
arbitrum = "${ARBITRUM_RPC_URL}"
base = "${BASE_RPC_URL}"
bsc = "${BSC_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"

[etherscan]
ethereum = { key = "${ETHERSCAN_API_KEY}" }
polygon = { key = "${POLYGONSCAN_API_KEY}" }
arbitrum = { key = "${ARBISCAN_API_KEY}" }
base = { key = "${BASESCAN_API_KEY}" }
bsc = { key = "${BSCSCAN_API_KEY}", url = "https://api.bscscan.com/api" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }
